INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (1,'Kitami Institute of Technology','北見工業大学','https://ror.org/05wks2t16','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (2,'Tohoku University','東北大学','https://ror.org/01dq60k83','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (3,'Iwate University','岩手大学','https://ror.org/04cd75h10','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (4,'National Institute of Informatics','国立情報学研究所','https://ror.org/04ksd4g47','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (5,'Toho University','東邦大学','https://ror.org/02hcx7n63','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (6,'Rikkyo University','立教大学','https://ror.org/00x194q47','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (7,'Showa University','昭和大学','https://ror.org/04mzk4q39','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (8,'Tokyo Gakugei University','東京学芸大学','https://ror.org/00khh5r84','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (9,'Gunma University','群馬大学','https://ror.org/046fm7598','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (10,'Keio University','慶応義塾大学','https://ror.org/02kn6nx58','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (11,'The University of Tokyo','東京大学','https://ror.org/057zh3y96','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (12,'Waseda University','早稲田大学','https://ror.org/00ntfnx83','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (13,'RIKEN','理化学研究所','https://ror.org/01sjwvz98','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (14,'Mie University','三重大学','https://ror.org/01529vy56','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (15,'Shinshu University','信州大学','https://ror.org/0244rem06','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (16,'Kanazawa University','金沢大学','https://ror.org/02hwp6a56','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (17,'Japan Advanced Institute of Science and Technology','北陸先端科学技術大学院大学','https://ror.org/03frj4r98','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (18,'National Institute for Fusion Science','核融合科学研究所(extic)','https://ror.org/01t3wyv61','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (19,'https://ror.org/02kpeqv85','京都大学','https://ror.org/02kpeqv85','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (20,'Kobe University','神戸大学','https://ror.org/03tgsfw79','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (21,'Ritsumeikan University','立命館大学','https://ror.org/0197nmd03','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (22,'Kansai University','関西大学','https://ror.org/03xg1f311','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (23,'Osaka Kyoiku University','大阪教育大学','https://ror.org/051j8zv27','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (24,'Kyoto Prefectural University','京都府立大学','https://ror.org/00ktqrd38','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (25,'Doshisha University','同志社大学','https://ror.org/01fxdkm29','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (26,'Osaka University','大阪大学','https://ror.org/035t8zc32','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (27,'Shiga University','滋賀大学','https://ror.org/01vvhy971','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (28,'Hiroshima University','広島大学','https://ror.org/03t78wx29','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (29,'Shimane University','島根大学','https://ror.org/01jaaym28','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (30,'Ehime University','愛媛大学','https://ror.org/017hkng22','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (31,'Tokushima University','徳島大学','https://ror.org/044vy1d05','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (32,'Saga University','佐賀大学','https://ror.org/04f4wg107','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (33,'Kyushu University','九州大学','https://ror.org/00p4k0j84','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (34,'Seinan Gakuin University','西南学院大学','https://ror.org/03jqhsn85','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (35,'Okinawa University','沖縄大学','https://ror.org/046zepm61','','');
INSERT INTO gf_db.affiliation (id,name,displayed_name,url,alias,description) VALUES (36,'Ritsumeikan Asia Pacific University','立命館アジア太平洋大学','https://ror.org/03ynn1n59','','');
