FROM ubuntu:18.04

RUN apt upgrade
RUN apt update

RUN apt install -y datalad

# get git-annex v8
RUN wget -O- http://neuro.debian.net/lists/bionic.jp.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
RUN apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com 0xA5D32F012649A5A9
RUN apt-get update
RUN apt-get install git-annex-standalone

WORKDIR /home/ivis/gogs
COPY . .

# install golang
RUN wget https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
RUN export PATH=$PATH:/usr/local/go/bin

RUN go install github.com/kevinburke/go-bindata/...
RUN export PATH=$PATH:/home/ivis/go/bin

# build gogs binary
RUN make build

CMD ["./gogs", "web"]
