name: Setup Host-Server Enviroment

on:
  workflow_dispatch:
    inputs:
      install_sudo:
        description: 'If "sudo" is not installed, check it.'
        required: true
        type: boolean
        default: false

jobs:

  build:
    runs-on: [self-hosted, development]

    steps:
    - name: Install sudo
      if: ${{ inputs.install_sudo }}
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install sudo
    - name: Install Dependency
      run: |
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose
        sudo apt-get install -y git
        sudo apt-get install -y wget
        sudo apt-get install -y make
        sudo apt-get install -y gcc
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'
    - run: echo "GOPATH="$GOROOT >> $GITHUB_ENV
    - run: echo "GOBIN="$GOPATH"/bin" >> $GITHUB_ENV
    - run: echo $GOBIN >> $GITHUB_PATH
    - name: Install Dependencies
      run: |
        go get -u github.com/kevinburke/go-bindata/...
