name: Setup Host-Server Enviroment

on: [ workflow_dispatch ]

jobs:

  build:
    runs-on: [self-hosted, development]

    steps:
    - name: Install sudo
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install sudo
    - name: Install Dependency
      run: |
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose
        sudo apt-get install -y git
        sudo apt-get install -y wget
        sudo apt-get install -y make
        sudo apt-get install -y gcc
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'
    - name: Install Dependencies
      run: |
        go get -u github.com/kevinburke/go-bindata/...
